package com.Edenred.runner;


import io.cucumber.junit.Cucumber;
import io.cucumber.junit.CucumberOptions;
import org.junit.runner.RunWith;

@RunWith(Cucumber.class)
@CucumberOptions(

        // This runner class will be pointing directly to the rerun.txt file that is generated by our plugin.
        //It will only have one job -->  When we run it, it will execute the "failed" scenarios that are stored in the rerun.txt

        glue = "com/Edenred/step_definitions", // ---> we pass step_definitions path
        features = "@target/rerun.txt"// ---> assists with generating of the failed tests report


        /*
Why do we need RERUN and FailedTestRunner?

    - Mostly to save time when tests fail
    - If we have hundreds of tests, and only few of them are failing, we don't want to execute all the hundreds of the tests again.
    - That's why we can just execute the failed tests that are automatically stored under the rerun.txt using our FailedTestRunner.

FailedTestRunner cannot change or edit the rerun.txt.

- Therefore even if the tests are passing, the lines will still in the rerun.txt, which is normal.
- We can delete rerun.txt by going Maven --> clean
 */
)
public class FailedTestRunner {
}
